import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import LayoutNavigation from "@/components/layout/navigation";
import HeadingComponent from "@/components/layout/heading";
import Footer from "@/components/footer";
import { Analytics } from "@vercel/analytics/react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Legal Space",
  description: "Generated by Zappy",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <HeadingComponent />
        <LayoutNavigation />
        {children}
        <Analytics />
        <Footer />
      </body>
    </html>
  );
}
